### ISSUE TITLE
Broken submodule

### ISSUE THREAD

**Issue by MacLotsen** [ThePhD/lua-bindings-shootout#6]
I've tried to install the submodules. I'm getting stuck on installing BaaMeow/benchmark.

Has the submodule been (re)moved?

**Comment by ThePhD** [comment]
Probably: you'll likely have to redirect to the proper google/benchmark repository.

We were using some novelty features out of the BaaMeow version but I think all the necessary data is in benchmark proper now.

**Comment by MacLotsen** [comment]
Thanks. That works for me. I'll probably include it when a pr is coming up.
